# Marvel character statz

In [1]:
# 3rd party imports
import polars as pl
import datetime as dt

In [2]:

df = pl.read_csv("../dta/marvel_sanitized_w_h.csv")

In [3]:
species = df.group_by("Species").len()
print(species)
type(species)

shape: (31, 2)
┌───────────────────┬─────┐
│ Species           ┆ len │
│ ---               ┆ --- │
│ str               ┆ u32 │
╞═══════════════════╪═════╡
│ Mutant / Clone    ┆ 1   │
│ Mutant            ┆ 47  │
│ Atlantean         ┆ 1   │
│ Zen-Whoberian     ┆ 1   │
│ -                 ┆ 109 │
│ …                 ┆ …   │
│ Animal            ┆ 1   │
│ Human / Radiation ┆ 9   │
│ Android           ┆ 2   │
│ God / Eternal     ┆ 1   │
│ Vampire           ┆ 2   │
└───────────────────┴─────┘

polars.dataframe.frame.DataFrame

In [9]:
species = species.sort(by="len", descending=True)
species

shape: (31, 2)
┌───────────────────┬─────┐
│ Species           ┆ len │
│ ---               ┆ --- │
│ str               ┆ u32 │
╞═══════════════════╪═════╡
│ -                 ┆ 112 │
│ Human             ┆ 76  │
│ Mutant            ┆ 47  │
│ Human / Radiation ┆ 9   │
│ Symbiote          ┆ 7   │
│ …                 ┆ …   │
│ God / Eternal     ┆ 1   │
│ Animal            ┆ 1   │
│ Zen-Whoberian     ┆ 1   │
│ Mutant / Clone    ┆ 1   │
│ Flora Colossus    ┆ 1   │
└───────────────────┴─────┘

In [10]:
nan = df.filter(pl.col("Species") == "-")

nan

shape: (112, 11)
┌─────┬────────────────┬───────────┬────────┬───┬───────────────┬───────────┬────────┬────────┐
│ ID  ┆ Name           ┆ Alignment ┆ Gender ┆ … ┆ Publisher     ┆ SkinColor ┆ Height ┆ Weight │
│ --- ┆ ---            ┆ ---       ┆ ---    ┆   ┆ ---           ┆ ---       ┆ ---    ┆ ---    │
│ i64 ┆ str            ┆ str       ┆ str    ┆   ┆ str           ┆ str       ┆ i64    ┆ i64    │
╞═════╪════════════════╪═══════════╪════════╪═══╪═══════════════╪═══════════╪════════╪════════╡
│ 40  ┆ Arclight       ┆ bad       ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 173    ┆ 57     │
│ 43  ┆ Ariel          ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 165    ┆ 59     │
│ 44  ┆ Armor          ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 163    ┆ 50     │
│ 61  ┆ Bantam         ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 165    ┆ 54     │
│ 71  ┆ Battlestar     ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 198    ┆ 133    │
│ …   ┆ …              ┆ …         ┆ …      ┆ … ┆ …             ┆ …         ┆ …      ┆ …      │
│ 718 ┆ Wolfsbane      ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 366    ┆ 473    │
│ 721 ┆ Wonder Man     ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 188    ┆ 171    │
│ 724 ┆ Wyatt Wingfoot ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 196    ┆ 117    │
│ 726 ┆ X-Man          ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 175    ┆ 61     │
│ 727 ┆ Yellow Claw    ┆ bad       ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 188    ┆ 95     │
└─────┴────────────────┴───────────┴────────┴───┴───────────────┴───────────┴────────┴────────┘

In [4]:
eter = df.filter(pl.col("Species") == "Eternal")

eter

shape: (2, 11)
┌─────┬──────────┬───────────┬────────┬───┬───────────────┬───────────┬────────┬────────┐
│ ID  ┆ Name     ┆ Alignment ┆ Gender ┆ … ┆ Publisher     ┆ SkinColor ┆ Height ┆ Weight │
│ --- ┆ ---      ┆ ---       ┆ ---    ┆   ┆ ---           ┆ ---       ┆ ---    ┆ ---    │
│ i64 ┆ str      ┆ str       ┆ str    ┆   ┆ str           ┆ str       ┆ i64    ┆ i64    │
╞═════╪══════════╪═══════════╪════════╪═══╪═══════════════╪═══════════╪════════╪════════╡
│ 337 ┆ Hyperion ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 183    ┆ 207    │
│ 657 ┆ Thanos   ┆ bad       ┆ Male   ┆ … ┆ Marvel Comics ┆ purple    ┆ 201    ┆ 443    │
└─────┴──────────┴───────────┴────────┴───┴───────────────┴───────────┴────────┴────────┘

In [6]:
w_max = df.filter(pl.col("Weight") > 300)

w_max

shape: (19, 11)
┌─────┬────────────────────┬───────────┬────────┬───┬───────────────┬───────────┬────────┬────────┐
│ ID  ┆ Name               ┆ Alignment ┆ Gender ┆ … ┆ Publisher     ┆ SkinColor ┆ Height ┆ Weight │
│ --- ┆ ---                ┆ ---       ┆ ---    ┆   ┆ ---           ┆ ---       ┆ ---    ┆ ---    │
│ i64 ┆ str                ┆ str       ┆ str    ┆   ┆ str           ┆ str       ┆ i64    ┆ i64    │
╞═════╪════════════════════╪═══════════╪════════╪═══╪═══════════════╪═══════════╪════════╪════════╡
│ 33  ┆ Anti-Venom         ┆ -         ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 229    ┆ 358    │
│ 119 ┆ Bloodaxe           ┆ bad       ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 218    ┆ 495    │
│ 217 ┆ Destroyer          ┆ bad       ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 188    ┆ 383    │
│ 233 ┆ Drax the Destroyer ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ green     ┆ 193    ┆ 306    │
│ 331 ┆ Hulk               ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ green     ┆ 244    ┆ 630    │
│ …   ┆ …                  ┆ …         ┆ …      ┆ … ┆ …             ┆ …         ┆ …      ┆ …      │
│ 591 ┆ She-Hulk           ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 201    ┆ 315    │
│ 657 ┆ Thanos             ┆ bad       ┆ Male   ┆ … ┆ Marvel Comics ┆ purple    ┆ 201    ┆ 443    │
│ 682 ┆ Ultron             ┆ bad       ┆ Male   ┆ … ┆ Marvel Comics ┆ silver    ┆ 206    ┆ 331    │
│ 691 ┆ Venom III          ┆ bad       ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 229    ┆ 334    │
│ 718 ┆ Wolfsbane          ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 366    ┆ 473    │
└─────┴────────────────────┴───────────┴────────┴───┴───────────────┴───────────┴────────┴────────┘

In [7]:
h_max = df.filter(pl.col("Height") > 200)

h_max

shape: (34, 11)
┌─────┬───────────────┬───────────┬────────┬───┬───────────────┬───────────┬────────┬────────┐
│ ID  ┆ Name          ┆ Alignment ┆ Gender ┆ … ┆ Publisher     ┆ SkinColor ┆ Height ┆ Weight │
│ --- ┆ ---           ┆ ---       ┆ ---    ┆   ┆ ---           ┆ ---       ┆ ---    ┆ ---    │
│ i64 ┆ str           ┆ str       ┆ str    ┆   ┆ str           ┆ str       ┆ i64    ┆ i64    │
╞═════╪═══════════════╪═══════════╪════════╪═══╪═══════════════╪═══════════╪════════╪════════╡
│ 29  ┆ Ant-Man       ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 211    ┆ 122    │
│ 33  ┆ Anti-Venom    ┆ -         ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 229    ┆ 358    │
│ 34  ┆ Apocalypse    ┆ bad       ┆ Male   ┆ … ┆ Marvel Comics ┆ grey      ┆ 213    ┆ 135    │
│ 78  ┆ Beta Ray Bill ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 201    ┆ 216    │
│ 119 ┆ Bloodaxe      ┆ bad       ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 218    ┆ 495    │
│ …   ┆ …             ┆ …         ┆ …      ┆ … ┆ …             ┆ …         ┆ …      ┆ …      │
│ 667 ┆ Thundra       ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 218    ┆ 158    │
│ 682 ┆ Ultron        ┆ bad       ┆ Male   ┆ … ┆ Marvel Comics ┆ silver    ┆ 206    ┆ 331    │
│ 691 ┆ Venom III     ┆ bad       ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 229    ┆ 334    │
│ 709 ┆ Warpath       ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 218    ┆ 158    │
│ 718 ┆ Wolfsbane     ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 366    ┆ 473    │
└─────┴───────────────┴───────────┴────────┴───┴───────────────┴───────────┴────────┴────────┘

### String operations

In [10]:
ind = df.filter(pl.col("Name").str.starts_with("Spider"))

ind

shape: (8, 11)
┌─────┬──────────────────┬───────────┬────────┬───┬───────────────┬───────────┬────────┬────────┐
│ ID  ┆ Name             ┆ Alignment ┆ Gender ┆ … ┆ Publisher     ┆ SkinColor ┆ Height ┆ Weight │
│ --- ┆ ---              ┆ ---       ┆ ---    ┆   ┆ ---           ┆ ---       ┆ ---    ┆ ---    │
│ i64 ┆ str              ┆ str       ┆ str    ┆   ┆ str           ┆ str       ┆ i64    ┆ i64    │
╞═════╪══════════════════╪═══════════╪════════╪═══╪═══════════════╪═══════════╪════════╪════════╡
│ 620 ┆ Spider-Girl      ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 170    ┆ 54     │
│ 621 ┆ Spider-Gwen      ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 165    ┆ 56     │
│ 622 ┆ Spider-Man       ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 178    ┆ 74     │
│ 623 ┆ Spider-Man       ┆ good      ┆ -      ┆ … ┆ Marvel Comics ┆ -         ┆ 178    ┆ 77     │
│ 624 ┆ Spider-Man       ┆ good      ┆ Male   ┆ … ┆ Marvel Comics ┆ -         ┆ 157    ┆ 56     │
│ 625 ┆ Spider-Woman     ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 178    ┆ 59     │
│ 627 ┆ Spider-Woman III ┆ good      ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 173    ┆ 55     │
│ 628 ┆ Spider-Woman IV  ┆ bad       ┆ Female ┆ … ┆ Marvel Comics ┆ -         ┆ 178    ┆ 58     │
└─────┴──────────────────┴───────────┴────────┴───┴───────────────┴───────────┴────────┴────────┘